clear;
close all;
clc;
disp('Finel Mode Shape Display');
disp('===== ==== ===== =======');
load(load_m_file);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h=figure;
set(h,'Position',[400 300 540 400]);
vph_handle=subplot('position',[0.08 0.05 0.4 0.4]);
vgr_handle=subplot('position',[0.08 0.55 0.4 0.4]);
ms1_handle=subplot('position',[0.58 0.05 0.4 0.4]);
ms2_handle=subplot('position',[0.58 0.55 0.4 0.4]);
view1=[-37.5 30];
view2=[0 0];
view3=[-37.5 30];
view4=[0,90];
i=figure;
set(i,'Position',[400 300 540 400])
large_ms_handle=axes;
%mode_sensitivity_figure=figure;
%set(mode_sensitivity_figure,'Position',[400 300 540 400])
%%%%%%%%%%%%%%%%%%%%%%%%
xi=linspace(0,0.16,100);
yi=linspace(-0.07,0.07,100);
[XI,YI]=meshgrid(xi,yi);
%%%%%%%%%%%%%%%%%%%%%%%%
data_mode_list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20;1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]';
mode_no=1;
point_no=1;
scale=512;
%freq=data_freq(data_mode_start_indices(mode_no)+point_no-1);
freq=16e3;
%freq_lims=[0 max(max(data_freq))];
freq_lims=[0 30e3];
ch=1;
while ch>0;
    index=point_no;
    point_no=find_nearest_point(data_mode_start_indices,data_freq,mode_no,freq);
    draw_mode_shape(data_nodes,data_els,data_ms_x,data_ms_y,data_ms_z,data_mode_start_indices,data_freq,mode_no,freq,scale,ms1_handle,view2);
    axis equal; axis tight;
    draw_mode_shape(data_nodes,data_els,data_ms_x,data_ms_y,data_ms_z,data_mode_start_indices,data_freq,mode_no,freq,scale,ms2_handle,view4);
    axis equal; axis tight;
    %draw_mode_shape(data_nodes,data_els,data_ms_x,data_ms_y,data_ms_z,data_mode_start_indices,data_freq,mode_no,freq,scale,large_ms_handle,view2);
    draw_vph(data_freq,data_ph_vel,mode_no,data_no_modes,data_mode_start_indices,freq,freq_lims,vph_handle);
    draw_vgr(data_freq,data_gr_vel,mode_no,data_no_modes,data_mode_start_indices,freq,freq_lims,vgr_handle);
    %%%%%%%%%%%%%%%%%%%%%%%%
    if 0
        figure(mode_sensitivity_figure);
        nodal_disp=(data_ms_x(:,point_no).^2)+(data_ms_y(:,point_no).^2)+(data_ms_z(:,point_no).^2);
        nodal_disp=nodal_disp-min(nodal_disp)+mean(nodal_disp);
        x=data_nodes(:,1);y=data_nodes(:,2);z=nodal_disp;
        x=x-6;
        ZI=griddata(x,y,z,XI,YI,'cubic');
        clf;surf(XI,YI,ZI);hold on;view(view3);shading interp;plot3(data_nodes(data_perimeter_node_list(:),1)-6,data_nodes(data_perimeter_node_list(:),2),data_nodes(data_perimeter_node_list(:),3),'k');
        caxis([0,max(nodal_disp)]);
        axis equal; axis tight;
        axis off
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    disp(strcat('Mode: ',num2str(data_mode_list(mode_no,1))));
    disp(strcat('Point: ',num2str(point_no)));
    disp(strcat('Scale: ',num2str(scale)));
    disp(strcat('Frequency: ',num2str(data_freq(point_no)/1000),'kHz'));
    disp(strcat('Phase velocity: ',num2str(data_ph_vel(point_no)/1000),'m/ms'));
    disp(strcat('Group velocity: ',num2str(data_gr_vel(point_no)/1000),'m/ms'));
    disp('Options');   
    disp(' ');
    disp('1. Next mode');
    disp('2. Previous mode');
    disp('3. Next point');
    disp('4. Previous point');
    disp('5. Increase mode shape scale');
    disp('6. Decrease mode shape scale');
    disp('7. Pick mode');
    disp('8. Pick frequency');
    disp('9. Change frequency limits');
    disp('10. Change view');
    disp('11. Keyboard input');
    disp('12. Export all mode shapes at current frequency');
    %   disp('10. Animate current');
    disp('0 . Quit');
    disp(' ');
    ch=input('Select: ');
    while isempty(ch);
        ch=input('Select: ');
    end;
    if (ch==1)&(mode_no<size(data_mode_start_indices,1));
        mode_no=mode_no+1;
        if freq<min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        if freq>max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        point_no=1;
    end;
    if (ch==2)&(mode_no>1);
        mode_no=mode_no-1;
        if freq<min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        if freq>max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        point_no=1;
    end;
    if (ch==3)&(point_no<(data_mode_start_indices(mode_no+1)-data_mode_start_indices(mode_no)));
        point_no=point_no+1;
        freq=data_freq(data_mode_start_indices(mode_no)+point_no-1);
    end;
    if (ch==4)&(point_no>1);
        point_no=point_no-1;
        freq=data_freq(data_mode_start_indices(mode_no)+point_no-1);
    end;
    if (ch==5);
        scale=scale*2;
    end;
    if (ch==6);
        scale=scale/2;
    end;
    if (ch==7);
        mode_no=input('Mode number: ');      
        if mode_no>data_no_modes;
            mode_no=data_no_modes;
        end;
        if mode_no<1;
            mode_no=1;
        end;
        if freq<min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        if freq>max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        point_no=1;
    end;
    if (ch==8);
        freq=input('Frequency (kHz):')*1000;
        if freq<min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=min(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        if freq>max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
            freq=max(data_freq(data_mode_start_indices(mode_no):data_mode_start_indices(mode_no+1)-1));
        end;
        point_no=1;
    end;
    if (ch==9);
        freq_lims(1)=input('Lower frequency limit (kHz):')*1000;
        freq_lims(2)=input('Upper frequency limit (kHz):')*1000;
    end;
    if (ch==10)
        p=input('Select plot (1=top, 2=bottom):');
        disp('Select view:');
        disp('1. Default 3D');
        disp('2. XY');
        disp('3. XZ');
        disp('4. YZ');
        v=input('Selection:');
        if v==1;
            temp=[-37.5 30];
        end;
        if v==2;
            temp=[0 90];
        end;
        if v==3;
            temp=[0 0];
        end;
        if v==4;
            temp=[90,0];
        end;
        if p==2;
            view1=temp;
        end;
        if p==1;
            view2=temp;
        end;
    end;
    if (ch==11)
        keyboard;
    end;
    if (ch==12);
        freq1=freq;
        first_time=1;
        for count=1:data_no_modes;
            if freq>=min(data_freq(data_mode_start_indices(count):data_mode_start_indices(count+1)-1))&freq<=max(data_freq(data_mode_start_indices(count):data_mode_start_indices(count+1)-1));
                disp_shape=draw_perim_mode_shape(data_nodes,data_ms_x,data_ms_y,data_ms_z,data_mode_start_indices,data_perimeter_node_list,data_freq,count,freq,scale,perim_ms_fig_no);         
                if first_time;
                    out_x=zeros(size(disp_shape,1),data_no_modes);
                    out_y=zeros(size(disp_shape,1),data_no_modes);
                    out_z=zeros(size(disp_shape,1),data_no_modes);
                    first_time=0;
                end;
                out_x(:,count)=disp_shape(:,1);
                out_y(:,count)=disp_shape(:,2);
                out_z(:,count)=disp_shape(:,3);
            end;
        end;
    end;
    
    
end;
close all;